import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/Card';
import { Button } from '../ui/Button';
import { Badge } from '../ui/Badge';
import { Award, Download } from 'lucide-react';

export default function EarnedCertificatesList({ certificates, isLoading }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>My Certificates</CardTitle>
        <CardDescription>View and download your earned certificates</CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="text-center py-12">
            <p className="text-muted-foreground">Loading certificates...</p>
          </div>
        ) : certificates.length === 0 ? (
          <div className="text-center py-12">
            <Award className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-muted-foreground">No certificates found. Certificates will appear here once they are generated by an admin.</p>
          </div>
        ) : (
          <div className="space-y-4">
            {certificates.map((cert) => (
              <Card key={cert.id || cert._id} className="hover:shadow-md transition-shadow">
                <CardHeader>
                  <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                    <div className="flex items-start gap-4 flex-1">
                      <div className="w-12 h-12 bg-gradient-primary rounded-lg flex items-center justify-center flex-shrink-0">
                        <Award className="w-6 h-6 text-white" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <CardTitle className="text-lg mb-1">{cert.courseName || "Certificate"}</CardTitle>
                        <CardDescription className="text-sm">
                          {cert.recipientName || "Recipient"}
                        </CardDescription>
                        <div className="flex flex-wrap gap-2 mt-2">
                          <Badge variant="outline" className="text-xs">
                            {cert.certificateType || "Completion"}
                          </Badge>
                          <Badge 
                            variant="outline" 
                            className={cert.status === "Active" ? "bg-green-50 text-green-700" : "text-xs"}
                          >
                            {cert.status || "Active"}
                          </Badge>
                        </div>
                      </div>
                    </div>
                    {cert.fileUrl && (
                      <Button 
                        size="sm" 
                        variant="outline"
                        onClick={() => window.open(cert.fileUrl, '_blank')}
                        className="flex-shrink-0"
                      >
                        <Download className="w-4 h-4 mr-2" />
                        Download
                      </Button>
                    )}
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
                    <div>
                      <span className="text-muted-foreground">Certificate Number:</span>
                      <p className="font-mono font-semibold mt-1">{cert.certificateNumber || "N/A"}</p>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Issue Date:</span>
                      <p className="font-medium mt-1">
                        {cert.issueDate ? new Date(cert.issueDate).toLocaleDateString() : "N/A"}
                      </p>
                    </div>
                    {cert.expiryDate && (
                      <div>
                        <span className="text-muted-foreground">Expiry Date:</span>
                        <p className="font-medium mt-1">
                          {new Date(cert.expiryDate).toLocaleDateString()}
                        </p>
                      </div>
                    )}
                    <div>
                      <span className="text-muted-foreground">Recipient Email:</span>
                      <p className="font-medium mt-1">{cert.recipientEmail || "N/A"}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
